export const actionTypesRedux = {
  SET_TODOS: "SET_TODOS",
  GET_MORE_TODOS: "GET_MORE_TODOS",
  UPDATE_TODO: "UPDATE_TODO",
  CREATE_TODO: "CREATE_TODO",
  DELETE_TODO: "DELETE_TODO",
  SET_POSTS: "SET_POSTS",
  GET_MORE_POSTS: "GET_MORE_POSTS",
  UPDATE_POST: "UPDATE_POST",
  CREATE_POST: "CREATE_POST",
  DELETE_POST: "DELETE_POST",
};
